image:
  repository: romanowalex/backend-todo-list
  tag: v2.0

profile: k8s

secrets:
  - name: GOOGLE_CLIENT_ID
    secretName: credentials
    secretKey: google-client-id
  - name: GOOGLE_CLIENT_SECRET
    secretName: credentials
    secretKey: google-client-id

metrics:
  path: "/backend/manage/prometheus"

liveness:
  path: "/backend/manage/health/liveness"

readiness:
  path: "/backend/manage/health/readiness"

resources:
  requests:
    cpu: 1
    memory: 2048Mi
  limits:
    cpu: 1
    memory: 2048Mi