version: "3.9"
services:
  selenoid:
    image: aerokube/selenoid:1.10.8
    container_name: selenoid
    command: [ "-conf", "/etc/selenoid/browsers.json", "-container-network", "common" ]
    ports:
      - "4444:4444"
    volumes:
      - ./docker/selenoid/:/etc/selenoid/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - common

  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.8
    container_name: selenoid-ui
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    ports:
      - "8880:8080"
    networks:
      - common

networks:
  common:
    name: common