version: "3.9"
services:
  postgres:
    image: library/postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  backend-todo-list:
    build: .
    image: romanowalex/backend-todo-list:v2.1
    container_name: backend-todo-list
    environment:
      SPRING_PROFILES_ACTIVE: docker
      OAUTH2_SECURITY_ENABLED: true
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID:-''}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET:-''}"
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://localhost:8080/backend/manage/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db-data:
