version: "3.9"
services:
  jaeger:
    image: "jaegertracing/all-in-one:1.57"
    container_name: jaeger
    ports:
      - "4318:4318"
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
