version: "3.9"
services:
  frontend-todo-list:
    image: romanowalex/frontend-todo-list:v2.0
    container_name: frontend-todo-list
    restart: on-failure
    environment:
      BACKEND_HOST: backend-todo-list
    ports:
      - "80:80"
    networks:
      default:
        aliases:
          - todo-list.ru