version: "3.9"
services:
  frontend-todo-list:
    image: romanowalex/frontend-todo-list:v2.0
    container_name: frontend-todo-list
    restart: on-failure
    ports:
      - "80:80"
    networks:
      common:
        aliases:
          - todo-list.ru

networks:
  common:
    name: common