---
ingress:
  host: moon.local

deployment:
  replicas: 1

configs:
  default:
    containers:
      browser:
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi

quota:
  moon:
    namespace: default

browsers:
  default:
    selenium:
      MicrosoftEdge:
        repository: quay.io/browser/microsoft-edge-stable
        default: "125.0"
      chrome:
        repository: quay.io/browser/google-chrome-stable
        default: "125.0"
      firefox:
        repository: quay.io/browser/firefox-mozilla-build
        default: "125.0"
      opera: null
      safari: null
