spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:postgres-service}:${DATABASE_PORT:5432}/${DATABASE_NAME:todo_list}
    username: ${DATABASE_USER:program}
    password: ${DATABASE_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none