spring:
  application.name: todo-list
  main.banner-mode: off
  profiles.active: local
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            redirect-uri: ${GOOGLE_REDIRECT_URI:{baseUrl}/login/oauth2/code/google}
          auth0:
            client-id: ${AUTH0_CLIENT_ID:7uHBa1xYenYPjX7UhOonuGhOWvxLUwYM}
            client-secret: ${AUTH0_CLIENT_SECRET:TbNIL8SJx38sDDweRqWsRaqWKU7Q6UrWr0f6DzKwlLh48892GE4KfoKR1cfIe87e}
            redirect-uri: ${AUTH0_REDIRECT_URI:{baseUrl}/login/oauth2/code/auth0}
            scope:
              - openid
              - email
              - profile
        provider:
          auth0:
            issuer-uri: ${AUTH0_ISSUER_URI:https://romanowalex.eu.auth0.com/}

server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: /backend
    session:
      cookie:
        http-only: off
        max-age: 86400

management:
  credentials:
    user: management
    password: test
    role: MANAGEMENT
  endpoint:
    health.probes.enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure.include: info,health,loggers,prometheus
  health.diskspace.enabled: false
  metrics.tags.application: ${spring.application.name}
  endpoint.health.show-details: always
  info.git.mode: simple
  health:
    readinessstate.enabled: true
    livenessstate.enabled: true

springdoc:
  api-docs.path: /api-docs
  paths-to-match: /api/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

oauth2:
  login:
    redirect-uri: /

index-page:
  enabled: ${INDEX_PAGE:true}