spring:
  application.name: todo-list
  main.banner-mode: off
  profiles.active: local

server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        http-only: off
        max-age: 86400

management:
  endpoint:
    health.probes.enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure.include: info,health,loggers,prometheus
  health.diskspace.enabled: false
  endpoint.health.show-details: always
  info.git.mode: simple
  health:
    readinessstate.enabled: true
    livenessstate.enabled: true

springdoc:
  api-docs.path: /api-docs
  paths-to-match: /api/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json