apiVersion: v1
kind: Service
metadata:
  name: backend-todo
  namespace: practice
  labels:
    app: backend-todo
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    app: backend-todo
