global:
  scrape_interval: 5s

scrape_configs:
  - job_name: backend
    metrics_path: '/backend/manage/prometheus'
    basic_auth:
      username: management
      password: 'test'
    static_configs:
      - targets: [ backend-todo-list:8080 ]

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: [ cadvisor:8080 ]
