name: Build project
on: [  workflow_dispatch ]
jobs:
  create-cluster:
    name: Create Cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  test:
    name: UI Test
    runs-on: ubuntu-latest
    needs: create-cluster
    steps:
      - uses: actions/checkout@v4

  publish-allure:
    name: Publish Allure report
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: jar
          path: build/allure-results/

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

  destroy-cluster:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    needs: [ test, create-cluster ]
    steps:
      - uses: actions/checkout@v4
